In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
## Create & Read

In [11]:
arr1 = np.array([1,2,3,4,5,6])

In [12]:
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [13]:
arr1.size

6

In [14]:
# 2D array

In [15]:
arr2 = np.array([[1,4,5], [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.size

6

#### 3D array

In [24]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3,5,5], [8,3,2]] , [[1,4,5],[6,7,4]]])

In [25]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 5],
        [8, 3, 2]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [21]:
arr3.ndim

3

In [26]:
arr3.shape #2 is no of layers, 2 is no of rows in each layer , 3 is no of columns in each layer

(3, 2, 3)

In [1]:
# CReate random array

In [4]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.07121525, 0.2114006 , 0.97434871],
        [0.23406561, 0.09935997, 0.17173143]],

       [[0.2928372 , 0.83592588, 0.58531601],
        [0.23026337, 0.72653441, 0.95295216]],

       [[0.08656535, 0.1828535 , 0.62854212],
        [0.28385928, 0.89688994, 0.54662398]]])

In [5]:
randomArr.dtype

dtype('float64')

In [6]:
randomArr.ndim

3

In [7]:
zeroes= np.zeros((3,2,3))

In [8]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
zeroes.ndim

3

In [11]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [12]:
ones = np.ones((3,3,3))

In [13]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
ones.ndim

3

In [19]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3,5,5], [8,3,2]] , [[1,4,5],[6,7,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 5],
        [8, 3, 2]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [20]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [24]:
arr3[0][1][1]

np.int64(7)

In [26]:
arr3[0:3]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 5],
        [8, 3, 2]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [28]:
arr3[1,0,1]

np.int64(5)

## Update and Delete Numpy Arrays

In [30]:
a1 = np.random.rand(2,3,2) 
a2 = np.random.rand(2,3,2)

In [31]:
a1

array([[[0.19768674, 0.51136631],
        [0.96965179, 0.65017266],
        [0.83582824, 0.04145753]],

       [[0.56217181, 0.04836678],
        [0.47013497, 0.11997654],
        [0.90640169, 0.29053378]]])

In [32]:
a2

array([[[0.6009951 , 0.13593913],
        [0.6531839 , 0.02524242],
        [0.90990983, 0.32310526]],

       [[0.24410447, 0.75173613],
        [0.87046741, 0.15457273],
        [0.45094919, 0.61220638]]])

In [33]:
np.add(a1, a2)

array([[[0.79868184, 0.64730544],
        [1.62283569, 0.67541508],
        [1.74573807, 0.36456279]],

       [[0.80627628, 0.80010291],
        [1.34060238, 0.27454927],
        [1.35735087, 0.90274016]]])

In [34]:
np.multiply(a1, a2)

array([[[0.11880876, 0.06951469],
        [0.63336094, 0.01641193],
        [0.76052833, 0.01339515]],

       [[0.13722865, 0.03635906],
        [0.40923717, 0.0185451 ],
        [0.4087411 , 0.17786663]]])

In [35]:
np.subtract(a1, a2)

array([[[-0.40330836,  0.37542718],
        [ 0.31646789,  0.62493024],
        [-0.07408159, -0.28164773]],

       [[ 0.31806735, -0.70336935],
        [-0.40033244, -0.03459619],
        [ 0.4554525 , -0.32167259]]])

In [36]:
np.divide(a1,a2)

array([[[ 0.32893237,  3.7617301 ],
        [ 1.48450045, 25.75714195],
        [ 0.91858359,  0.12830968]],

       [[ 2.30299683,  0.06434011],
        [ 0.54009486,  0.77618177],
        [ 2.0099863 ,  0.47456837]]])

In [37]:
# statistical operation

In [40]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [41]:
sqrt

np.float64(5.0)

In [42]:
abs

np.int64(2)

In [43]:
power

np.int64(256)

In [44]:
log

np.float64(3.2188758248682006)

In [45]:
mins

np.float64(0.041457533797110147)

In [46]:
maxs

np.float64(0.9099098318218177)

In [47]:
arr3[0,0,2] = 6

In [48]:
arr3

array([[[1, 4, 6],
        [6, 7, 4]],

       [[3, 5, 5],
        [8, 3, 2]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [51]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[1, 4, 6],
        [6, 7, 4],
        [3, 5, 5]],

       [[8, 3, 2],
        [1, 4, 5],
        [6, 7, 4]]])

#Appending & Inserting

In [52]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
#Create a new array
new_array = np.ones((3,2,3))

In [54]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
appd = np.append(zeroes, new_array, axis=1)
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#Insert

In [57]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [63]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [64]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.72891725, 0.95397417, 0.67312893],
        [0.64385333, 0.88932389, 0.94649332]],

       [[0.32674788, 0.21570057, 0.84178428],
        [0.02499585, 0.00478019, 0.35548427]],

       [[0.70908668, 0.93158077, 0.59624614],
        [0.27412795, 0.42270483, 0.46977174]]])

In [67]:
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.64385333, 0.88932389, 0.94649332]],

       [[0.02499585, 0.00478019, 0.35548427]],

       [[0.27412795, 0.42270483, 0.46977174]]])

In [68]:
np.save("new_array", arr5)

In [69]:
np.load("new_array.npy")

array([[[0.64385333, 0.88932389, 0.94649332]],

       [[0.02499585, 0.00478019, 0.35548427]],

       [[0.27412795, 0.42270483, 0.46977174]]])